# Generated by Django 3.2 on 2021-04-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeNum', models.IntegerField(max_length=16, verbose_name='关注数量')),
                ('fansNum', models.IntegerField(max_length=16, verbose_name='粉丝数量')),
                ('location_city', models.CharField(max_length=16, verbose_name='所在城市')),
            ],
        ),
    ]
